<a href="https://colab.research.google.com/github/javierriveroiglesias-design/Computational-Physics/blob/main/Exams/Test_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Computational Methods, Test 1

1. (5 points) Use the following NumPy Arrays to evaluate the Python commands below:



```
x[3]

x[:3]

y[-1]

y[y>4]

x[y==8]
```



In [3]:
import numpy as np
x = np.array([3, 6, 7, 2, 0, 2, 5, 5])
y = np.array([0, 5, 2, 8, 4, 5, 1, 8])

# x[3] is going to give [3]
# x[:3] is going to give [3 6 7]
# y[-1] is going to give [8]
# y[y>4] is going to give [5 8 5 8]
# x[y==8] is going to give [2 5]

# enter your code here
print(x[3])

print(x[:3])

print(y[-1])

print(y[y>4])

print(x[y==8])

2
[3 6 7]
8
[5 8 5 8]
[2 5]


2. (5 points) Write down the output of the following commands


In [4]:
np.linspace(0,5,5)
np.arange(0,10,2)
np.zeros((2,4))

# linspace is going to give [0 1 2 3 4]
# arange is going to give [0 2 4 6 8]
# zeros is going to give 2 rows and 4 columns of zeros
# [0 0 0 0
#  0 0 0 0}

print(np.linspace(0,5,5))
print(np.arange(0,10,2))
print(np.zeros((2,4)))

[0.   1.25 2.5  3.75 5.  ]
[0 2 4 6 8]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3. (5 points) Calculate the sum of the squares of integers from 1 to 100. Use any method.


In [6]:
# enter your code here
total = 0
for i in range (1,101):
    total += i**2
print(total)

338350


4. (5 points) Given a Python list of integers A, create a new list B that only contains those elements of A that are positive. Use a for loop (not logical indexing).


In [7]:
# enter your code here
A = [-1, 2, -3, 4, 5, -6, 7, -8, 9, 10, -11, -12, -1000]
B = []

for num in A:
    if num > 0:
        B.append(num)
print(B)

[2, 4, 5, 7, 9, 10]


5. (5 points) (a) Write down the output of the following Python program in the box below. Only show what will be printed.

In [8]:
A = [1, -2, 3, -4, 5, -6]
s1 = 0
s2 = 0
for n in A:
     if n > 0:
         s1 += n
     else:
         s2 += n
     print(f'{n:2} {s1:2} {s2:2}')

# The code is going to create three columns with the first column being the index for elements in the array.
# The second column is going to be for the positive numbers in the array being added up.
# The third column is going to be for negative numbers in the array being added up.

 1  1  0
-2  1 -2
 3  4 -2
-4  4 -6
 5  9 -6
-6  9 -12


6. (5 points) (a) Write down the output of the following Python program in the box below. Only show what will be printed.


In [9]:
s = 0
for n in range(4):
    for x in range(n+1):
       s += 1
    print(f'{n}  {s}')

# The code above is going to create two columns of rows.
# The first column is going to be the index for elements in the range.
# The second is going to be for 's' which is going to add +1 to the value or number before it until it reaches 3.

0  1
1  3
2  6
3  10


7. (5 points) Write some Python code using the NumPy library to calculate the speed of an object in free fall:
Prompt the user to enter the height $h$ from which the object is dropped.
Calculate the velocity using $v=\sqrt{2gh}$ , where $g=9.8$ m/s$^2$.
Print a message displaying and labeling the velocity rounded to 2 decimal places
Print a warning message if the speed exceeds half the speed of light, where $c=3\times 10^8$ m/s. The message should read:  “The object is approaching the speed of light”.

In [10]:
# enter your code here
g = 9.8 # m/s^2
c = 3e8 # m/s

h = float(input("Enter an interger for a height: "))

v = np.sqrt(2*g*h)

print(f"The velocity of the object for height {h} is {v} m/s")

if v > (0.5*c):
    print("This object is approaching the speed of light")

Enter an interger for a height: 10
The velocity of the object for height 10.0 is 14.0 m/s


8. (5 points) Create a  NumPy array (100 rows and 4 columns) containing the following:
* Column 1:  angle $\theta$ - linearly spaced values between 0 and
* Column 2: $\sin \theta$  
* Column 3: $\cos \theta$
* Column 4:  average of the values in columns 2 and 3

In [13]:
# enter your code here
theta = np.linspace(0,np.pi,100)
sintheta = np.sin(theta)
costheta = np.cos(theta)
avg = ((sintheta + costheta)/2)
data = np.column_stack((theta,sintheta,costheta,avg))

print(data)

[[ 0.00000000e+00  0.00000000e+00  1.00000000e+00  5.00000000e-01]
 [ 3.17332591e-02  3.17279335e-02  9.99496542e-01  5.15612238e-01]
 [ 6.34665183e-02  6.34239197e-02  9.97986676e-01  5.30705298e-01]
 [ 9.51997774e-02  9.50560433e-02  9.95471923e-01  5.45263983e-01]
 [ 1.26933037e-01  1.26592454e-01  9.91954813e-01  5.59273633e-01]
 [ 1.58666296e-01  1.58001396e-01  9.87438889e-01  5.72720142e-01]
 [ 1.90399555e-01  1.89251244e-01  9.81928697e-01  5.85589971e-01]
 [ 2.22132814e-01  2.20310533e-01  9.75429787e-01  5.97870160e-01]
 [ 2.53866073e-01  2.51147987e-01  9.67948701e-01  6.09548344e-01]
 [ 2.85599332e-01  2.81732557e-01  9.59492974e-01  6.20612765e-01]
 [ 3.17332591e-01  3.12033446e-01  9.50071118e-01  6.31052282e-01]
 [ 3.49065850e-01  3.42020143e-01  9.39692621e-01  6.40856382e-01]
 [ 3.80799110e-01  3.71662456e-01  9.28367933e-01  6.50015194e-01]
 [ 4.12532369e-01  4.00930535e-01  9.16108457e-01  6.58519496e-01]
 [ 4.44265628e-01  4.29794912e-01  9.02926538e-01  6.66360725e

9. (5 points) In this problem, you will explore a random walk in which the motion of a particle is controlled by a coin toss. If the coin is heads, move one unit to the right (+1), if tails, move one unit to the left (–1). Here’s the procedure:
* Ask the user to input the total number of steps for the random walk
* Start the particle at the origin.
* Pick a random number to move the particle left or right by one unit.
* Repeat for a total of N steps
* After the walk is complete, print the position of the particle

     You can use any method you like to solve this problem

In [14]:
# enter your code here

import random

N = int(input("Enter a interger for a total number of steps: "))
position = 0

for _ in range(N):
    step = random.choice([-1,1])
    position += step
print(f"Your final position for this experiment is {position} for {N} number of total steps.")

Enter a interger for a total number of steps: 10
Your final position for this experiment is 2 for 10 number of total steps.


10. (5 points) The Liebnitz formula for pi is:

$\pi \approx 4 \sum_{k=o}^N \frac{(-1)^k}{2k+1}  \approx 4\cdot \left[ 1-\frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9}+ \cdots \right]$
                             
* Write some Python code that prompts the user for the upper limit on the summation N and calculates the series.
* Calculate the percent error of your approximation:  $error=\left| \frac{estimate-actual}{actual} \right|\times 100\%$

* print your estimated value of pi and the percent error along with a descriptive message
* Use any method you like.

In [18]:
# enter your code here

N = int(input("Enter a number to be an upper limit 'N' for summation: "))
pisum = 0

for k in range(N+1):
    pisum += ((-1)**k/(2*k+1))
pisum *= 4

realpi = np.pi
error = abs((pisum - realpi/realpi)*100)

print(f"The estimated value for pi with {N} as upper limit is {pisum}")
print(f"The percent error for estimated value of pi is {error}")
print(f"Value of pi is {np.pi}")

Enter a number to be an upper limit 'N' for summation: 10
The estimated value for pi with 10 as upper limit is 3.232315809405594
The percent error for estimated value of pi is 223.23158094055938
Value of pi is 3.141592653589793
