<a href="https://colab.research.google.com/github/javierriveroiglesias-design/Computational-Physics/blob/main/Exams/Test_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Computational Methods, Test 1

1. (5 points) Use the following NumPy Arrays to evaluate the Python commands below:



```
x[3]

x[:3]

y[-1]

y[y>4]

x[y==8]
```



In [2]:
import numpy as np
x = np.array([3, 6, 7, 2, 0, 2, 5, 5])
y = np.array([0, 5, 2, 8, 4, 5, 1, 8])

# enter your code here
# x[3] will show the [2]
# x[:3] will show [3 6 7]
# y[-1] will show [8]
# y[y>4] will show all values greatear than 4 in y array, so [5 8 5 8]
# x[y==8] will show all values from y array in which 8 is equal to in x array, so [2 5]

print(x[3])

print(x[:3])

print(y[-1])

print(y[y>4])

print(x[y==8])

2
[3 6 7]
8
[5 8 5 8]
[2 5]


2. (5 points) Write down the output of the following commands


In [3]:
np.linspace(0,5,5)
np.arange(0,10,2)
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
# linespace will create will create an array from 0-5 which will be [0 1 2 3 4]
# arange will create an array from 0-10 by 2 which will be [0 2 4 6 8]
# zeros will create an array with 2 rows and 4 columns filled with 0's
print(np.linspace(0,5,5))
print(np.arange(0,10,2))
print(np.zeros((2,4)))

[0.   1.25 2.5  3.75 5.  ]
[0 2 4 6 8]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3. (5 points) Calculate the sum of the squares of integers from 1 to 100. Use any method.


In [17]:
# enter your code here
total = 0
for i in range (1,101):
    total += i**2
print(total)

338350


4. (5 points) Given a Python list of integers A, create a new list B that only contains those elements of A that are positive. Use a for loop (not logical indexing).


In [19]:
# enter your code here[
A = [-1, -4, -6, -1000, -1354212, 1231, 2, 323, 4341, 123, -21, 2321, -12, 2113, -312]
B = []
for num in A:
    if num > 0:
        B.append(num)
print(B)

[1231, 2, 323, 4341, 123, 2321, 2113]


5. (5 points) (a) Write down the output of the following Python program in the box below. Only show what will be printed.

In [20]:
# what I think the python code will do below is create 3 columns and the first column will be 1-6 because it's going to list the elements in the array.
# the second column is going to be all positive numbers from the array and they're going to be added on to another as the for loop runs.
# the third column is going to be all the negative numbers from the array and bee added on to each other as well.
A = [1, -2, 3, -4, 5, -6]
s1 = 0
s2 = 0
for n in A:
     if n > 0:
         s1 += n
     else:
         s2 += n
     print(f'{n:2} {s1:2} {s2:2}')

 1  1  0
-2  1 -2
 3  4 -2
-4  4 -6
 5  9 -6
-6  9 -12


6. (5 points) (a) Write down the output of the following Python program in the box below. Only show what will be printed.


In [8]:
# what's I think is going to happen in this code it'll have two columns, the first being the index and elements for the range and the second column being for the 's' value which is going to add +1 in the range 4 to the value number before it.
s = 0
for n in range(4):
    for x in range(n+1):
       s += 1
    print(f'{n}  {s}')

0  1
1  3
2  6
3  10


7. (5 points) Write some Python code using the NumPy library to calculate the speed of an object in free fall:
Prompt the user to enter the height $h$ from which the object is dropped.
Calculate the velocity using $v=\sqrt{2gh}$ , where $g=9.8$ m/s$^2$.
Print a message displaying and labeling the velocity rounded to 2 decimal places
Print a warning message if the speed exceeds half the speed of light, where $c=3\times 10^8$ m/s. The message should read:  “The object is approaching the speed of light”.

In [9]:
# enter your code here

8. (5 points) Create a  NumPy array (100 rows and 4 columns) containing the following:
* Column 1:  angle $\theta$ - linearly spaced values between 0 and
* Column 2: $\sin \theta$  
* Column 3: $\cos \theta$
* Column 4:  average of the values in columns 2 and 3

In [10]:
# enter your code here

9. (5 points) In this problem, you will explore a random walk in which the motion of a particle is controlled by a coin toss. If the coin is heads, move one unit to the right (+1), if tails, move one unit to the left (–1). Here’s the procedure:
* Ask the user to input the total number of steps for the random walk
* Start the particle at the origin.
* Pick a random number to move the particle left or right by one unit.
* Repeat for a total of N steps
* After the walk is complete, print the position of the particle

     You can use any method you like to solve this problem

In [11]:
# enter your code here

10. (5 points) The Liebnitz formula for pi is:

$\pi \approx 4 \sum_{k=o}^N \frac{(-1)^k}{2k+1}  \approx 4\cdot \left[ 1-\frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9}+ \cdots \right]$
                             
* Write some Python code that prompts the user for the upper limit on the summation N and calculates the series.
* Calculate the percent error of your approximation:  $error=\left| \frac{estimate-actual}{actual} \right|\times 100\%$

* print your estimated value of pi and the percent error along with a descriptive message
* Use any method you like.

In [12]:
# enter your code here